tidyverse/duckplyr

- R/dplyr.R
- R/summarise.R
- patch/summarise.patch
Two tests currently fail:
``` r
pkgload::load_all()
#> ℹ Loading duckplyr
df <- tibble(g = c(1, 1, 2, 2, 2), x = 1:5)
duckplyr_summarise(df, out = !!1)
#> materializing:
#> ---------------------
#> --- Relation Tree ---
#> ---------------------
#> Aggregate [1.0]
#>   r_dataframe_scan(0x107a96648)
#> 
#> ---------------------
#> -- Result Columns  --
#> ---------------------
#> - out (DOUBLE)
#> 
#> # A tibble: 5 × 1
#>     out
#>   <dbl>
#> 1     1
#> 2     1
#> 3     1
#> 4     1
#> 5     1
summarise(df, out = !!1)
#> # A tibble: 1 × 1
#>     out
#>   <dbl>
#> 1     1
duckplyr_summarise(df, out = !!quo(1))
#> materializing:
#> ---------------------
#> --- Relation Tree ---
#> ---------------------
#> Aggregate [1.0]
#>   r_dataframe_scan(0x125943b48)
#> 
#> ---------------------
#> -- …
```
> Implement summarise()

- tools/34-tpch-bench.R
Adjustments to the benchmarking scripts. Change META_GLOBAL to META skip for better execution results that don't materialize intermediate results.
> Benchmarking adjustments

- R/tpch.R
- R/tpch2.R
- tools/36-tpch-bench-compare.R
In order to run the queries on both dplyr and duckdb with no errors or other changes required, we need to revert the prefix and suffix optimizations that were made. 
With the addition of https://github.com/duckdb/duckdb/pull/7181 data frames are scanned in parallel, so these optimizations aren't as necessary as before.
https://github.com/duckdb/duckdb/pull/7264 will also be merged after the release sometime.
> Revert prefix suffix optimizations, revert year extraction

- DESCRIPTION
- R/oo.R
- R/union_all.R
- patch/union_all.patch
- tests/testthat/test-rel_api.R
- tools/00-funs.R
> feat: Order-stable `union_all()`

- R/arrange.R
- R/count.R
- R/distinct.R
- R/dplyr.R
- R/filter.R
- R/head.R
- R/intersect.R
- R/mutate.R
- R/project.R
- R/setdiff.R
- R/symdiff.R
- R/transmute.R
- README.Rmd
- README.md
- patch/arrange.patch
- patch/count.patch
- patch/distinct.patch
- patch/filter.patch
- patch/intersect.patch
- patch/mutate.patch
- patch/setdiff.patch
- patch/symdiff.patch
- patch/transmute.patch
- tests/testthat/_snaps/expr.md
- tests/testthat/test-overwrite.R
Obsolete with https://github.com/tidyverse/dplyr/pull/6927.
> fix: Use `dplyr_reconstruct_dispatch()` to avoid issues with R >= 4.3

- README.Rmd
- README.md
Fix #34 
Other tweaks
- put installation instructions at the beginning.
- extract nearly all comments (apart from the CAVEAT that is inside a pipeline) from code chunks to make them more readable.
- clarify the titles of example sections.
- add link and short explanation of DuckDB.
> docs: small README improvements

- R/relational.R
- R/summarise.R
- patch/summarise.patch
- tests/testthat/test-as_duckplyr_df.R
- tools/03-tests.R
> fix: `summarise()` keeps `"duckplyr_df"` class

- R/distinct.R
> fix: `distinct()` now preserves order in corner cases

- README.Rmd
- README.md
For something on the package's readme, it slowed me down from appreciating how cool this package is.
> separate & explain the new relational examples

- DESCRIPTION
- R/arrange.R
- R/count.R
- R/distinct.R
- R/filter.R
- R/intersect.R
- R/mutate.R
- R/relational.R
- R/relocate.R
- R/rename.R
- R/select.R
- R/setdiff.R
- R/summarise.R
- R/symdiff.R
- R/telemetry.R
- R/transmute.R
- R/union_all.R
- tests/testthat/_snaps/telemetry.md
- tests/testthat/test-telemetry.R
For #102.
@hadley @DavisVaughan: Proposing data for the telemetry. Have I missed anything?
> chore: Add calls for telemetry

- R/fallback.R
Note - I've not changed the test snapshot in case you have a preferred system for updating in place.
> fix: Correct wording in instructions for enabling fallback logging

- R/head.R
- tests/testthat/test-head.R
> fix: `head(-1)` forwards to the default implementation

- R/intersect.R
- R/setdiff.R
- R/symdiff.R
- R/union_all.R
- patch/intersect.patch
- patch/setdiff.patch
- patch/symdiff.patch
- patch/union_all.patch
> fix: Stricter type checks in the set operations `intersect()`, `setdiff()`, `symdiff()`, `union()`, and `union_all()`

- R/arrange.R
- R/relational-duckdb.R
- R/relational-rel.R
- man/new_relational.Rd
Closes #92.
Creating a `desc` macro feels a bit like a work-around as it is created for the sole purpose of not raising a function-not-found -error. Couldn't think of an easy alternative. What do you think @krlmlr ?
> feat: Support descending sort for character and other non-numeric data

- R/fallback.R
``` r
options(conflicts.policy = list(warn = FALSE))
library(duckplyr)
#> The duckplyr package is configured to fall back to dplyr when it encounters an
#> incompatibility. Fallback events can be collected and uploaded for analysis to
#> guide future development. By default, no data will be collected or uploaded.
#> → Run `duckplyr::fallback_sitrep()` to review the current settings.
#> ✔ Overwriting dplyr methods with duckplyr methods.
#> ℹ Turn off with `duckplyr::methods_restore()`.
```
<sup>Created on 2024-07-11 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
> docs: Shorter startup message

- .github/CONTRIBUTING.md
- DESCRIPTION
- R/fallback.R
- README.Rmd
- README.md
- _pkgdown.yml
- gh-analysis/README.md
- man/duckplyr-package.Rd
- man/fallback.Rd
- tools/90-patch-dplyr.R
> docs: Move to tidyverse

- R/as_duckplyr_tibble.R
> feat: `as_duckplyr_tibble()` supports dbplyr connections to a duckdb database

- R/duckplyr-package.R
Hi,
If `options(duckdb.materialize_message = FALSE)` is specified in the `.Rprofile` file, it will be overridden by
```
on_load({
if (!identical(Sys.getenv("TESTTHAT"), "true")) {
options(duckdb.materialize_message = TRUE)
}
})
```
when starting an `.Rproj`. I suggest checking if the option is already specified and maybe setting the default to `FALSE` as mentioned in #209. 
Thanks & all the best!
> feat: Set the `duckdb.materialize_message` option on load only if not previously specified

- R/telemetry.R
- tests/testthat/_snaps/telemetry.md
- tests/testthat/test-telemetry.R
> fix: `expr_scrub()` can handle function-definitions

- R/zzz.R
- tests/testthat/test-mutate.R
- tools/00-funs.R
Closes #217.
``` r
options(conflicts.policy = list(warn = FALSE))
library(duckplyr)
#> The duckplyr package is configured to fall back to dplyr when it encounters an
#> incompatibility. Fallback events can be collected and uploaded for analysis to
#> guide future development. By default, no data will be collected or uploaded.
#> → Run `duckplyr::fallback_sitrep()` to review the current settings.
#> ✔ Overwriting dplyr methods with duckplyr methods.
#> ℹ Turn off with `duckplyr::methods_restore()`.
environment(dplyr:::summarise.data.frame)
#> <environment: namespace:dplyr>
environment(getS3method("summarise", "data.frame"))
#> <environment: namespace:duckplyr>
```
<sup>Created on 2024-10-16 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
> fix: Attaching duckplyr via `library()` overwrites all dplyr methods again

- DESCRIPTION
- R/duckplyr-across.R
- R/zzz.R
- tests/testthat/_snaps/duckplyr-across.md
- tests/testthat/test-duckplyr-across.R
Follow-up to #296.
This removes the need to keep the expressions used in the call to `across()` for the case of package functions. Non-package functions cannot be translated with duckplyr anyway at this stage.
This passes all tests, scheduling for merge, appreciate a review anyway.
> feat: More complete `across()`

- R/mutate.R
For #270.
@toppyy: I believe this is the only instance of `rel_translate()` that gets called without `data` . This will simplify your PR. Appreciate your thoughts.
> feat: `mutate()` constructs intermediate data frames for each new variable

- R/fallback.R
> docs: Avoid `\code{}`

- R/relational-duckdb.R
- R/translate.R
- tests/testthat/test-as_duckplyr_df.R
- tools/00-funs.R
- vignettes/limits.Rmd
Adds translation for sub and gsub to regexp_replace. No related issue.
No support for parameters beyond pattern, replacement and x.
> feat: Add support for `sub()` and `gsub()`

- R/fallback.R
- R/telemetry.R
- tests/testthat/_snaps/fallback.md
- tests/testthat/test-fallback.R
> feat: Fallback logging is now on by default, can be disabled with configuration

- R/config.R
- R/fallback.R
- R/relational.R
- man/config.Rd
- man/fallback.Rd
- tests/testthat/_snaps/fallback.md
- tests/testthat/_snaps/relational.md
- tests/testthat/test-fallback.R
> docs: Prefer `DUCKPLYR_FALLBACK_INFO` over `DUCKPLYR_FALLBACK_VERBOSE`

- R/collect.R
- tests/testthat/test-as_duckplyr_df.R
- tests/testthat/test-compute_file.R
- tests/testthat/test-lazy.R
- tools/00-funs.R
> feat: `collect()` returns a tibble

- R/config.R
- R/relational-duckdb.R
- man/config.Rd
> feat: The default DuckDB connection is now based on a file, the location can be controlled with the `DUCKPLYR_TEMP_DIR` environment variable

- R/ducktbl.R
- tests/testthat/_snaps/ducktbl.md
@lionel- @DavisVaughan @hadley: I'm trying out this pattern for getting a clean source of error, see the snapshot diff at https://github.com/tidyverse/duckplyr/pull/468/files#diff-e6f6630cd5973ffe606db6f51980c092691e89bd56970e58edf3f03711aab6e7R6 . Is there a cleaner way to achieve this?
> chore: Clean up source in error

- R/collect-rd.R
- R/compute-rd.R
- R/mutate-rd.R
- _pkgdown.yml
- man/collect.duckplyr_df.Rd
- man/compute.duckplyr_df.Rd
- man/mutate.duckplyr_df.Rd
> docs: Tweak reference index

- R/fallback.R
- tests/testthat/_snaps/fallback.md
- tests/testthat/test-fallback.R
> fix: Remove startup message after second `load_all()`

- vignettes/funnel.Rmd
I believe you wanted to say
> for a funneled frame with `funnel = TRUE`, fallbacks to dplyr are not possible.
Not 
> for a funneled frame with `funnel = FALSE`, fallbacks to dplyr are not possible.
That said, this commit removes any mention of the argument as it seems a little superfluous given the surrounding examples.
> docs: Fix erroneous argument

- R/ducktbl.R
- R/funnel.R
- R/io2.R
- R/relational.R
- R/sql.R
- man/compute.duckplyr_df.Rd
- man/compute_file.Rd
- man/duckdb_tibble.Rd
- man/read_file_duckdb.Rd
- tests/testthat/test-compute_file.R
- tests/testthat/test-ducktbl.R
- tests/testthat/test-funnel.R
- tests/testthat/test-sql.R
- vignettes/developers.Rmd
- vignettes/funnel.Rmd
> docs: Change `funnel` values to `"open"` and `"closed"` instead of a logical value

- R/relational-duckdb.R
- R/tpch.R
- R/tpch2.R
- R/translate.R
- README.Rmd
- README.md
- index.md
- tests/testthat/_snaps/tpch.md
- tests/testthat/_snaps/translate.md
- tests/testthat/test-as_duckplyr_df.R
- tests/testthat/test-dplyr-mutate.R
- tests/testthat/test-translate.R
> feat: Implement `na.rm` handling for `sum()`, `min()`, `max()`, `any()` and `all()`, with fallback for window functions

- DESCRIPTION
- NEWS.md
- cran-comments.md
> fledge: CRAN release v1.0.0

- vignettes/fallback.Rmd
> docs: improve fallbacks vignette

- R/filter.R
Got this error as I tried replacing the pivoting example in the post.
> docs: Fix typo in `filter(.by = ...)` error message

- DESCRIPTION
- NEWS.md
- cran-comments.md
Running examples in ‘duckplyr-Ex.R’ failed
The error most likely occurred in:
> ### Name: read_file_duckdb
> ### Title: Read Parquet, CSV, and other files using DuckDB
> ### Aliases: read_file_duckdb read_parquet_duckdb read_csv_duckdb
> ###   read_json_duckdb
> 
> ### ** Examples
> 
> # Create simple CSV file
> path <- tempfile("duckplyr_test_", fileext = ".csv")
> write.csv(data.frame(a = 1:3, b = letters[4:6]), path, row.names = FALSE)
> 
> # Reading is immediate
> df <- read_csv_duckdb(path)
> 
> # Names are always available
> names(df)
[1] "a" "b"
> 
> # Materialization upon access is turned off by default
> try(print(df$a))
[1] 1 2 3
> 
> # Materialize explicitly
> collect(df)$a
[1] 1 2 3
> 
> # Automatic materialization with prudence = "lavish"
> df <- read_csv_duckdb(path, …
> fledge: CRAN release v1.0.1
