README.Rmd
README.md

Fix #62
However some sort of order might still be needed? I see other lines in the diff, however if I knit again I don't get any difference.

docs: Add stability to README output

---

DESCRIPTION
NEWS.md
cran-comments.md

CRAN release v0.2.2

---

DESCRIPTION
NEWS.md
cran-comments.md

{{{ crp_changes }}}
{{{ check_cran_comments }}}
- Run `fledge::release()`{{{ fledge_gha_workflow_release }}}
- Confirm CRAN e-mail
- When the package is accepted on CRAN, run `fledge::post_release()`{{{ fledge_gha_workflow_release }}}

CRAN release v0.2.3

---

R/relational-duckdb.R
tests/testthat/test-as_duckplyr_df.R
tools/00-funs.R

fix: Consistent computation of `log(0)` and `log(-1)`

---

R/count.R
R/summarise.R
R/telemetry.R
tests/testthat/_snaps/telemetry.md

chore: Better scrubbing for telemetry

---

R/fallback.R
man/fallback.Rd

I probably should have only changed source but did Rd file as well

docs: telementry -> telemetry

---

R/as_duckplyr_df.R
R/relational-duckdb.R
R/relational.R
R/telemetry.R
patch/anti_join.patch
patch/count.patch
patch/full_join.patch
patch/inner_join.patch
patch/left_join.patch
patch/right_join.patch
patch/semi_join.patch
patch/summarise.patch
tests/testthat/_snaps/count-tally.md
tests/testthat/_snaps/fallback.md
tests/testthat/_snaps/select.md
tests/testthat/_snaps/sets.md
tests/testthat/_snaps/telemetry.md
tests/testthat/_snaps/transmute.md
tests/testthat/setup.R
tests/testthat/test-as_duckplyr_df.R
tests/testthat/test-deprec-do.R
tests/testthat/test-fallback.R
tests/testthat/test-group-map.R
tools/00-funs.R

fix: Improve and test fallback telemetry

---

DESCRIPTION
NEWS.md
cran-comments.md

- Groom `NEWS.md` and `cran-comments.md`
- Wait for successful tests
- If needed, tweak and review PR
- Run `fledge::release()`
- Confirm CRAN e-mail
- When the package is accepted on CRAN, run `fledge::post_release()` (often handled by GitHub Actions)

CRAN release v0.3.2

---

R/io-csv.R
R/io.R
man/df_from_file.Rd

docs: Mention wildcards to read multiple files in `?df_from_file`

---

DESCRIPTION
tests/testthat/setup.R

chore: Remove styler dependency

---

DESCRIPTION
NEWS.md
cran-comments.md

- Groom `NEWS.md` and `cran-comments.md`
- Wait for successful tests
- If needed, tweak and review PR
- Run `fledge::release()`
- Confirm CRAN e-mail
- When the package is accepted on CRAN, run `fledge::post_release()` (often handled by GitHub Actions)

CRAN release v0.4.0

---

R/io.R
man/df_from_file.Rd

docs: Show how to read multiple files

---

R/io-csv.R
man/df_from_file.Rd

docs: Show how to specify CSV column types

---

README.Rmd
README.md

docs: Discuss dbplyr in README

---

R/io-.R
man/df_from_file.Rd

feat: `df_from_file()` and related functions support multiple files

---

DESCRIPTION
NEWS.md
cran-comments.md

- Groom `NEWS.md` and `cran-comments.md`
- Wait for successful tests
- If needed, tweak and review PR
- Run `fledge::release()`
- Confirm CRAN e-mail
- When the package is accepted on CRAN, run `fledge::post_release()` (often handled by GitHub Actions)

CRAN release v0.4.1

---

_pkgdown.yml

docs: Enable plausible

---

.github/workflows/R-CMD-check.yaml
.github/workflows/commit/action.yml
.github/workflows/dep-suggests-matrix/action.R
R/as_duckplyr_tibble.R
man/as_duckplyr_df.Rd

Fix cut-and-paste typo introduced when switching to as_duckplyr_tibble()

docs: Fix cut-and-paste typo

---

DESCRIPTION
R/tpch.R
R/tpch2.R
R/translate.R
tests/testthat/_snaps/demo.md
tests/testthat/test-demo.R
tests/testthat/test-prom.R
tools/07-overwrite.R
tools/36-tpch-bench-compare.R
tools/38-tpch-empty.R

For https://github.com/tidyverse/tidyverse/pull/346.

feat: Allow R 4.0

---

man/figures/lifecycle-deprecated.svg
man/figures/lifecycle-experimental.svg
man/figures/lifecycle-stable.svg
man/figures/lifecycle-superseded.svg

chore: Add lifecycle badges

---

R/duckplyr_execute.R
man/duckplyr_execute.Rd

docs: Add link to DuckDB configuration

---

R/config.R
R/fallback.R
R/relational.R
R/telemetry.R
README.Rmd
README.md
index.md
man/config.Rd
tests/testthat/_snaps/fallback.md

docs: Adapt README and tests for telemetry

---

vignettes/large.Rmd

docs: Remove use of word bottleneck

---

vignettes/large.Rmd

docs: Document limiting memory usage

---

R/handle_desc.R
R/relational.R
R/translate.R
tests/testthat/_snaps/fallback.md
tests/testthat/_snaps/handle_desc.md
tests/testthat/_snaps/translate.md
tests/testthat/test-handle_desc.R

docs: Show error source for translation errors

---

R/exec.R
man/db_exec.Rd
vignettes/large.Rmd

docs: explicitly state how to change DuckDB configuration options

---

R/filter-rd.R
man/filter.duckplyr_df.Rd

fix: Fix link in documentation
